--- #YAML:1.0
name:                IPC-Gnuplot
version:             0.01
abstract:            A class for managing an IPC to gnuplot
license:             ~
author:              
    - Ari Jolma <ari.jolma @ tkk.fi>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
