--- #YAML:1.0
name:         Gtk2-Ex-Geo
version:      0.61
abstract:     A framework of widgets for geospatial applications
licence:      Artistic
author:              
    - Ari Jolma <ari.jolma @ tkk.fi>
requires:
  ExtUtils::Depends: 0
  ExtUtils::PkgConfig: 0
  Gtk2::GladeXML: 0
  Graphics::ColorUtils: 0
  Geo::OGC::Geometry: 0
build_requires:
  ExtUtils::Depends: 0
  ExtUtils::PkgConfig: 0

meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
